apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vault-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-vault-demo
  template:
    metadata:
      labels:
        app: nginx-vault-demo
    spec:
      containers:
      - name: nginx
        image: openresty/openresty:1.19.9.1-0-alpine
        command: ["nginx"]
        args: ["-g", "daemon off;"]
        ports:
        - containerPort: 8080
        env:
        - name: MY_SECRET
          valueFrom:
            secretKeyRef:
              name: my-nginx
              key: MY_SECRET
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: my-nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-nginx
data:
  nginx.conf: |
    events {}
    env MY_SECRET;
    http {
        server {
            listen 8080;
            location / {
                return 200 "${MY_SECRET}";
            }
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: my-nginx
stringData:
  MY_SECRET: "test-secret-value"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-vault-demo
spec:
  selector:
    app: nginx-vault-demo
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP





# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-vault-demo
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nginx-vault-demo
#   template:
#     metadata:
#       labels:
#         app: nginx-vault-demo
#     spec:
#       containers:
#       - name: nginx
#         image: openresty/openresty:1.19.9.1-0-alpine
#         ports:
#         - containerPort: 8080
#         envFrom:
#         - secretRef:
#             name: my-nginx
#         volumeMounts:
#         - name: nginx-config
#           mountPath: /etc/nginx/nginx.conf
#           subPath: nginx.conf
#       volumes:
#       - name: nginx-config
#         configMap:
#           name: my-nginx
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: my-nginx
# data:
#   nginx.conf: |
#     events {}
    
#     http {
#         server {
#             listen 8080;
            
#             location / {
#                 default_type text/plain;
#                 return 200 $ENV{"MY_SECRET"};
#             }
#         }
#     }
# # apiVersion: v1
# # kind: ConfigMap
# # metadata:
# #   name: my-nginx
# # data:
# #   nginx.conf: |
# #     events {}
# #     env MY_SECRET;
# #     http {
# #         server {
# #             listen 8080;
# #             location / {
# #                 set_by_lua \$my_secret 'return os.getenv("MY_SECRET")';
# #                 return 200 \$my_secret;
# #             }
# #         }
# #     }
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-vault-demo
# spec:
#   selector:
#     app: nginx-vault-demo
#   ports:
#   - port: 80
#     targetPort: 8080
#   type: ClusterIP
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: my-nginx
#   annotations:
#     avp.kubernetes.io/path: "secret/data/nginx"
# stringData:
#   MY_SECRET: <password>

